### ISSUE TITLE
Puzzle Proposal - Part 2 - Learn Practice Master Loop Doc

### ISSUE THREAD

**Issue by MattBlack343** [UoSGamesGroups/first-semester-l4-5-group-6#16]
1 Hour

Show how you can teach the player your mechanic.
How they can Practice is safely .
Then When they've mastered it put it to use to get past the main obstacle.

Think about keeping the player in the flow channel where the tasks gradually get harder as the player progresses.

**Comment by dannybeales** [comment]
Uploaded to Git Hub Part 1 & 2 Doc - Didnt spend 1 hour on this as i'll spend more time doing this within the prototype i hope tomorrow.
