### ISSUE TITLE
Seperate models out from the design level.

### ISSUE THREAD

**Issue by moccy** [UoSGamesGroups/first-semester-l4-5-group-6#28]
Move each model in to their own file instead of the entire level in one file.

4 hour

**Comment by MattBlack343** [comment]
2 hours
uploaded floor tile and box assets with norm map and diffuse colour.

**Comment by MattBlack343** [comment]
2hours
created conveybelt, 2nd tilable texture for grav wall, door placeholder, structural element test for 
new level concept.
