### ISSUE TITLE
Character Part 1 - Research 

### ISSUE THREAD

**Issue by MattBlack343** [UoSGamesGroups/first-semester-l4-5-group-6#7]
1 HOUR

In this task i'd like you to carry out research into what character would be the best design choice to achieve our goals.
eg.
- how we create empathy for the MC , 'such as a weakness'
  -striking silhouette

I'm leaning towards a less human character for ease of creation of assets

i would like you to work through this fast and collect a lot of materials/ source images . list examples of similar characters. etc in part 2 you'll distill them down.

As always commit files and email when complete for me to check them.

thanks

**Comment by JamieGostling** [comment]
Total Time Spent On Task: **2 hours 30 mins**
